### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by Sev7nrayne** [maxnatamo/arrexporter#1]
Where does one find the following?
- INFLUX_TOKEN=my-super-secret-auth-token
- INFLUX_ORG=arrexporter
- INFLUX_BUCKET=arrexporter

I am currently using influxdb with Varken (Plex-influx-Grafana aggregator)
version: '3'
services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8.10
    network_mode: "bridge"
    ports:
      - 8086:8086
    environment:
      - PUID=100
      - PGID=100
      - TZ=America/New_York
      - INFLUXDB_DATABASE:varken

I want to use arrexporter to pull in radarr data as Varken does not support it at this time.
what configs do I need to import radarr data into the influxdb I already have

**Comment by Sev7nrayne** [comment]
error message:
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'INFLUX_TOKEN')
   at ArrExporter.Core.Broker.InitializeInfluxClient() in /src/ArrExporter.Core/Broker.cs:line 108
   at ArrExporter.Core.Broker.Initialize() in /src/ArrExporter.Core/Broker.cs:line 26
   at ArrExporter.Core.Program.Main(String[] args) in /src/ArrExporter.Core/Program.cs:line 16
   at ArrExporter.Core.Program.<Main>(String[] args)

**Comment by maxnatamo** [comment]
Hello! Thank you for reporting an issue.

I haven't worked with this in a while, but I remember both the organization and bucket being set, when you create InfluxDB. According to the docs, you need to set it using the environment variables specified [here](https://hub.docker.com/_/influxdb):
`DOCKER_INFLUXDB_INIT_ORG`
`DOCKER_INFLUXDB_INIT_BUCKET`

To create a new token, you can read the official InfluxDB docs [here](https://docs.influxdata.com/influxdb/v2/admin/tokens/create-token/#create-a-token-using-the-influx-cli).

Hope this help.
